export default {
  logout: 'Log out',
  loggedOut: 'You are now logged out.',
  cart: 'Go to Cart',
  home: 'Home',
  profile: 'Profile',
  shoppingHistory: 'Shopping History',
  oops: 'Ooops!',
  notImplemented: 'This page is not implemented yet :/',
  preferences: 'Preferences',
  grocery: 'Grocery',
  kitchen: 'Kitchen Tools',
  car: 'Car Tools',
  fetchArticlesListStart: 'Loading articles',
  fetchArticlesListSuccess: 'Articles loaded.',
  fetchArticlesListFailure: 'Failed to load articles',
  fetchMeStart: 'Loading profile',
  fetchMeSuccess: 'Profile loaded.',
  fetchMeFailure: 'Failed to load profile'
}
